### ISSUE TITLE
Crie uma consulta que busca informações de usuarios de forma páginada.

### ISSUE THREAD

**Issue by meirellesh** [meirellesh/goservice#72]
Permita a consulta de usuarios por página. Para isso crie uma consulta personalizada para usuários que receba o numero da página e retorne apenas 10 resultados.

Referências: 

- https://www.mysqltutorial.org/mysql-limit.aspx

**Comment by GabrielFontes3094** [comment]
Feito a busca de 10 usuarios por vez para cada pagina.
Correção: Task interligada com a do front end.
